# Generated by Django 5.2 on 2025-04-12 20:56

from django.db import migrations

def migrate_balance(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.all():
        user = profile.user
        user.balance = profile.balance
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_balance),
    ]
