# Generated by Django 5.2 on 2025-04-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
