# Generated by Django 5.2 on 2025-04-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_guest'),
    ]

    operations = [
    ]
