# Generated by Django 5.2 on 2025-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('image', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_newsar_publish_db2481_idx')],
            },
        ),
    ]
