# Generated by Django 5.2 on 2025-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
