# Generated by Django 5.2 on 2025-04-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Utilities', 'Utilities'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investments', 'Investments'), ('Consulting', 'Consulting'), ('Online Sales', 'Online Sales'), ('Gifts', 'Gifts')], max_length=20),
        ),
    ]
